
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Timeline</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="stylesheet" type="text/css" href="/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/line-awesome.css">
    <link rel="stylesheet" type="text/css" href="/css/line-awesome-font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" type="text/css" href="/lib/slick/slick.css">
    <link rel="stylesheet" type="text/css" href="/lib/slick/slick-theme.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/responsive.css">
</head>


<body>


<div class="wrapper">



    <header>
        <div class="container">
            <div class="header-data">
                <div class="logo">
                    <a href="index.html" title=""><img src="images/logo.png" alt=""></a>
                </div><!--logo end-->
                <nav>
                    <ul>
                        <li>
                            <a href="index.html" title="">
                                <span><img src="images/icon1.png" alt=""></span>
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="companies.html" title="">
                                <span><img src="images/icon2.png" alt=""></span>
                                Companies
                            </a>
                            <ul>
                                <li><a href="companies.html" title="">Companies</a></li>
                                <li><a href="company-profile.html" title="">Company Profile</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="projects.html" title="">
                                <span><img src="images/icon3.png" alt=""></span>
                                Projects
                            </a>
                        </li>
                        <li>
                            <a href="profiles.html" title="">
                                <span><img src="images/icon4.png" alt=""></span>
                                Profiles
                            </a>
                            <ul>
                                <li><a href="user-profile.html" title="">User Profile</a></li>
                                <li><a href="my-profile-feed.html" title="">my-profile-feed</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="jobs.html" title="">
                                <span><img src="images/icon5.png" alt=""></span>
                                Jobs
                            </a>
                        </li>
                        <li>
                            <a href="#" title="" class="not-box-open">
                                <span><img src="images/icon6.png" alt=""></span>
                                Messages
                            </a>
                            <div class="notification-box msg">
                                <div class="nt-title">
                                    <h4>Setting</h4>
                                    <a href="#" title="">Clear all</a>
                                </div>
                                <div class="nott-list">
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img1.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="messages.html" title="">Jassica William</a> </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do.</p>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img2.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="messages.html" title="">Jassica William</a></h3>
                                            <p>Lorem ipsum dolor sit amet.</p>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img3.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="messages.html" title="">Jassica William</a></h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempo incididunt ut labore et dolore magna aliqua.</p>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="view-all-nots">
                                        <a href="messages.html" title="">View All Messsages</a>
                                    </div>
                                </div><!--nott-list end-->
                            </div><!--notification-box end-->
                        </li>
                        <li>
                            <a href="#" title="" class="not-box-open">
                                <span><img src="images/icon7.png" alt=""></span>
                                Notification
                            </a>
                            <div class="notification-box">
                                <div class="nt-title">
                                    <h4>Setting</h4>
                                    <a href="#" title="">Clear all</a>
                                </div>
                                <div class="nott-list">
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img1.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img2.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img3.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="notfication-details">
                                        <div class="noty-user-img">
                                            <img src="images/resources/ny-img2.png" alt="">
                                        </div>
                                        <div class="notification-info">
                                            <h3><a href="#" title="">Jassica William</a> Comment on your project.</h3>
                                            <span>2 min ago</span>
                                        </div><!--notification-info -->
                                    </div>
                                    <div class="view-all-nots">
                                        <a href="#" title="">View All Notification</a>
                                    </div>
                                </div><!--nott-list end-->
                            </div><!--notification-box end-->
                        </li>
                    </ul>
                </nav><!--nav end-->
                <div class="menu-btn">
                    <a href="#" title=""><i class="fa fa-bars"></i></a>
                </div><!--menu-btn end-->
                <div class="user-account">
                    <div class="user-info">
                        <img src="http://via.placeholder.com/30x30" alt="">
                        <a href="#" title="">John</a>
                        <i class="la la-sort-down"></i>
                    </div>
                    <div class="user-account-settingss">
                        <h3>Online Status</h3>
                        <ul class="on-off-status">
                            <li>
                                <div class="fgt-sec">
                                    <input type="radio" name="cc" id="c5">
                                    <label for="c5">
                                        <span></span>
                                    </label>
                                    <small>Online</small>
                                </div>
                            </li>
                            <li>
                                <div class="fgt-sec">
                                    <input type="radio" name="cc" id="c6">
                                    <label for="c6">
                                        <span></span>
                                    </label>
                                    <small>Offline</small>
                                </div>
                            </li>
                        </ul>
                        <h3>Custom Status</h3>
                        <div class="search_form">
                            <form>
                                <input type="text" name="search">
                                <button type="submit">Ok</button>
                            </form>
                        </div><!--search_form end-->
                        <h3>Setting</h3>
                        <ul class="us-links">
                            <li><a href="profile-account-setting.html" title="">Account Setting</a></li>
                            <li><a href="#" title="">Privacy</a></li>
                            <li><a href="#" title="">Faqs</a></li>
                            <li><a href="#" title="">Terms & Conditions</a></li>
                        </ul>
                        <h3 class="tc"><a href="sign-in.html" title="">Logout</a></h3>
                    </div><!--user-account-settingss end-->
                </div>
            </div><!--header-data end-->
        </div>
    </header><!--header end-->

    <main>
        <div class="main-section">
            <div class="container">
                <div class="main-section-data">
                    <div class="row">
                        <div class="col-lg-3 col-md-4 pd-left-none no-pd">
                            <div class="main-left-sidebar no-margin">
                                <div class="user-data full-width">
                                    <div class="user-profile">
                                        <div class="username-dt">
                                            <div class="usr-pic">
                                                <img src="/images/${user.avator!'default-avator.png'}" alt="">
                                            </div>
                                        </div><!--username-dt end-->
                                        <div class="user-specs">
                                            <h3>${user.username}</h3>
                                            <span>${user.about!"这个人很懒，什么都没有留下"}</span>
                                        </div>
                                    </div><!--user-profile end-->
                                    <ul class="user-fw-status">
                                        <li>
                                            <h4>Following</h4>
                                            <span>34</span>
                                        </li>
                                        <li>
                                            <h4>Followers</h4>
                                            <span>155</span>
                                        </li>
                                        <li>
                                            <a href="#" title="">View Profile</a>
                                        </li>
                                    </ul>
                                </div><!--user-data end-->
                                <div class="tags-sec full-width">
                                    <ul>
                                        <li><a href="#" title="">Help Center</a></li>
                                        <li><a href="#" title="">About</a></li>
                                        <li><a href="#" title="">Privacy Policy</a></li>
                                        <li><a href="#" title="">Community Guidelines</a></li>
                                        <li><a href="#" title="">Cookies Policy</a></li>
                                        <li><a href="#" title="">Career</a></li>
                                        <li><a href="#" title="">Language</a></li>
                                        <li><a href="#" title="">Copyright Policy</a></li>
                                    </ul>
                                    <div class="cp-sec">
                                        <img src="images/logo2.png" alt="">
                                        <p><img src="images/cp.png" alt="">Copyright 2018</p>
                                    </div>
                                </div><!--tags-sec end-->
                            </div><!--main-left-sidebar end-->
                        </div>
                        <div class="col-lg-6 col-md-8 no-pd">
                            <div class="main-ws-sec">
                                <div class="post-topbar">
                                    <div class="job_post">
                                        <div class="post-project">
                                            <div class="post-project-fields">
                                                <form method="get" action="/weibo/add">
                                                    <div class="row">
                                                        <div class="col-lg-12">
                                                            <input type="text" name="content" placeholder="Weibo">
                                                        </div>

                                                        <div class="col-lg-12">
                                                            <ul>
                                                                <li><button class="active" type="submit" value="post">Post</button></li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div><!--post-project-fields end-->
                                            <a href="#" title=""><i class="la la-times-circle-o"></i></a>
                                        </div><!--post-project end-->
                                    </div><!--post-project-popup end-->
                                    <!--										<form>-->
                                    <!--										<div class="user-picy">-->
                                    <!--											<textarea type="password" name="password" placeholder="Password" rows="5" cols="50"></textarea>-->
                                    <!--										</div>-->
                                    <!--										<div class="post-st">-->
                                    <!--											<ul>-->
                                    <!--												<li><a class="post-jb active" href="#" title="">Post a Job</a></li>-->
                                    <!--											</ul>-->
                                    <!--										</div>&lt;!&ndash;post-st end&ndash;&gt;-->
                                    <!--										</form>-->
                                </div><!--post-topbar end-->
                                <div class="posts-section">
                                    <#list weibos as weibo>
                                        <div class="posty">
                                            <div class="post-bar no-margin">
                                                <div class="post_topbar">
                                                    <div class="usy-dt">
                                                        <img src="http://via.placeholder.com/50x50" alt="">
                                                        <div class="usy-name">
                                                            <h3>${weibo.username!}</h3>
                                                            <span><img src="images/clock.png" alt="">${weibo.time!"0 min ago"}</span>
                                                        </div>
                                                    </div>
                                                    <div class="ed-opts">
                                                        <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                                                        <ul class="ed-options">
                                                            <li><a href="/weibo/edit?id=${weibo.id}" title="">Edit Post</a></li>
                                                            <li><a href="/weibo/delete?id=${weibo.id}" title="">Delete Post</a></li>
                                                        </ul>
                                                    </div>
                                                </div>
                                                <div class="job_descp">
                                                    <p>${weibo.content}</p>
                                                    <div class="post-comment">
                                                        <div class="cm_img">
                                                            <img src="http://via.placeholder.com/40x40" alt="">
                                                        </div>
                                                        <div class="comment_box">
                                                            <form action="/comment/add" method="get">
                                                                <input name="id" value="${weibo.id}" hidden/>
                                                                <input name="content" type="text" placeholder="Post a comment">
                                                                <button type="submit">Send</button>
                                                            </form>
                                                        </div>
                                                    </div><!--post-comment end-->
                                                </div>

                                            </div><!--post-bar end-->

                                                <div class="comment-section">

                                                    <#list weibo.comments as comment>
                                                    <div class="comment-sec">
                                                        <ul>
                                                            <li>
                                                                <div class="comment-list">
                                                                    <div class="bg-img">
                                                                        <img src="http://via.placeholder.com/40x40" alt="">
                                                                    </div>
                                                                    <div class="comment">
                                                                        <h3>${comment.username!"游客"}</h3>
                                                                        <span><img src="images/clock.png" alt="">${comment.updatetime!}</span>
                                                                        <p>${comment.content} </p>
                                                                    </div>
                                                                </div><!--comment-list end-->

                                                            </li>

                                                        </ul>
                                                    </div><!--comment-sec end-->
                                                    </#list>

                                                </div><!--comment-section end-->

                                        </div><!--posty end-->
                                    </#list>
                                </div><!--posts-section end-->
                            </div><!--main-ws-sec end-->
                        </div>
                        <div class="col-lg-3 pd-right-none no-pd">
                            <div class="right-sidebar">
                                <div class="widget widget-about">
                                    <img src="/images/wd-logo.png" alt="">
                                    <h3>Track Time on Workwise</h3>
                                    <span>Pay only for the Hours worked</span>
                                    <div class="sign_link">
                                        <h3><a href="#" title="">Sign up</a></h3>
                                        <a href="#" title="">Learn More</a>
                                    </div>
                                </div><!--widget-about end-->
                                <!--									<div class="widget widget-jobs">-->
                                <!--										<div class="sd-title">-->
                                <!--											<h3>Top Jobs</h3>-->
                                <!--											<i class="la la-ellipsis-v"></i>-->
                                <!--										</div>-->
                                <!--										<div class="jobs-list">-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior Product Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior UI / UX Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Junior Seo Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior PHP Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior Developer Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--										</div>&lt;!&ndash;jobs-list end&ndash;&gt;-->
                                <!--									</div>&lt;!&ndash;widget-jobs end&ndash;&gt;-->
                                <!--									<div class="widget widget-jobs">-->
                                <!--										<div class="sd-title">-->
                                <!--											<h3>Most Viewed This Week</h3>-->
                                <!--											<i class="la la-ellipsis-v"></i>-->
                                <!--										</div>-->
                                <!--										<div class="jobs-list">-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior Product Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Senior UI / UX Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--											<div class="job-info">-->
                                <!--												<div class="job-details">-->
                                <!--													<h3>Junior Seo Designer</h3>-->
                                <!--													<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit..</p>-->
                                <!--												</div>-->
                                <!--												<div class="hr-rate">-->
                                <!--													<span>$25/hr</span>-->
                                <!--												</div>-->
                                <!--											</div>&lt;!&ndash;job-info end&ndash;&gt;-->
                                <!--										</div>&lt;!&ndash;jobs-list end&ndash;&gt;-->
                                <!--									</div>&lt;!&ndash;widget-jobs end&ndash;&gt;-->
                                <!--									<div class="widget suggestions full-width">-->
                                <!--										<div class="sd-title">-->
                                <!--											<h3>Most Viewed People</h3>-->
                                <!--											<i class="la la-ellipsis-v"></i>-->
                                <!--										</div>&lt;!&ndash;sd-title end&ndash;&gt;-->
                                <!--										<div class="suggestions-list">-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>Jessica William</h4>-->
                                <!--													<span>Graphic Designer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>John Doe</h4>-->
                                <!--													<span>PHP Developer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>Poonam</h4>-->
                                <!--													<span>Wordpress Developer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>Bill Gates</h4>-->
                                <!--													<span>C &amp; C++ Developer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>Jessica William</h4>-->
                                <!--													<span>Graphic Designer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--											<div class="suggestion-usd">-->
                                <!--												<img src="http://via.placeholder.com/35x35" alt="">-->
                                <!--												<div class="sgt-text">-->
                                <!--													<h4>John Doe</h4>-->
                                <!--													<span>PHP Developer</span>-->
                                <!--												</div>-->
                                <!--												<span><i class="la la-plus"></i></span>-->
                                <!--											</div>-->
                                <!--										</div>&lt;!&ndash;suggestions-list end&ndash;&gt;-->
                                <!--									</div>-->
                            </div><!--right-sidebar end-->
                        </div>
                    </div>
                </div><!-- main-section-data end-->
            </div>
        </div>
    </main>




    <!--		<div class="post-popup pst-pj">-->
    <!--			<div class="post-project">-->
    <!--				<h3>Post a project</h3>-->
    <!--				<div class="post-project-fields">-->
    <!--					<form>-->
    <!--						<div class="row">-->
    <!--							<div class="col-lg-12">-->
    <!--								<input type="text" name="title" placeholder="Title">-->
    <!--							</div>-->
    <!--							<div class="col-lg-12">-->
    <!--								<div class="inp-field">-->
    <!--									<select>-->
    <!--										<option>Category</option>-->
    <!--										<option>Category 1</option>-->
    <!--										<option>Category 2</option>-->
    <!--										<option>Category 3</option>-->
    <!--									</select>-->
    <!--								</div>-->
    <!--							</div>-->
    <!--							<div class="col-lg-12">-->
    <!--								<input type="text" name="skills" placeholder="Skills">-->
    <!--							</div>-->

    <!--						</div>-->
    <!--					</form>-->
    <!--				</div>&lt;!&ndash;post-project-fields end&ndash;&gt;-->
    <!--				<a href="#" title=""><i class="la la-times-circle-o"></i></a>-->
    <!--			</div>&lt;!&ndash;post-project end&ndash;&gt;-->
    <!--		</div>&lt;!&ndash;post-project-popup end&ndash;&gt;-->

    <!--		<div class="post-popup job_post">-->
    <!--			<div class="post-project">-->
    <!--				<h3>Post a job</h3>-->
    <!--				<div class="post-project-fields">-->
    <!--					<form>-->
    <!--						<div class="row">-->
    <!--							<div class="col-lg-12">-->
    <!--								<input type="text" name="title" placeholder="Title">-->
    <!--							</div>-->

    <!--							<div class="col-lg-12">-->
    <!--								<ul>-->
    <!--									<li><button class="active" type="submit" value="post">Post</button></li>-->
    <!--									<li><a href="#" title="">Cancel</a></li>-->
    <!--								</ul>-->
    <!--							</div>-->
    <!--						</div>-->
    <!--					</form>-->
    <!--				</div>&lt;!&ndash;post-project-fields end&ndash;&gt;-->
    <!--				<a href="#" title=""><i class="la la-times-circle-o"></i></a>-->
    <!--			</div>&lt;!&ndash;post-project end&ndash;&gt;-->
    <!--		</div>&lt;!&ndash;post-project-popup end&ndash;&gt;-->




</div><!--theme-layout end-->



<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/popper.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/jquery.mCustomScrollbar.js"></script>
<script type="text/javascript" src="/lib/slick/slick.min.js"></script>
<script type="text/javascript" src="/js/scrollbar.js"></script>
<script type="text/javascript" src="/js/script.js"></script>

</body>
</html>